
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hospital
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
volumes:
  postgres_data: